# -*- coding: utf-8 -*-
"""air quality index

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p5kwWBd595uQ0XDVORj6smxrwrksvXyu
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from fbprophet import Prophet

data = pd.read_csv("AirQualityUCI.csv",delimiter=';')

data.head()

data.drop(['Unnamed: 15','Unnamed: 16'],axis =1, inplace = True)

data.head()

data.dropna()

data = data.dropna()

data

data['Date'] = pd.to_datetime(data['Date'],format="%d/%m/%Y")

data.head()

data['Date'].value_counts()

data.index = pd.DatetimeIndex(data['Date'])

data.resample('M').mean()

plt.plot(data.resample('M').mean())

data = data.resample('D').mean()

data = data.sort_values('Date')

data.head()

data.reset_index()

data = data.rename(columns={'Date	':'ds','PT08.S1(CO)':'y','NMHC(GT)':'y1','PT08.S2(NMHC)':'y2','NOx(GT)':'y3','PT08.S3(NOx)':'y4','NO2(GT)':'y5','PT08.S4(NO2)':'y6','PT08.S5(O3)':'y7'})

data = data.reset_index()

data = data.rename(columns= {'Date':'ds'})

data

m = Prophet()

column = ['y','y1','y2','y3','y4','y5','y6','y7']
for col in column:
  df_new = data[['ds',col]]
  df_new = df_new.rename(columns = {col:'y'})
  m = Prophet()
  m.fit(df_new)
  x = m.make_future_dataframe(periods = 400)
  y = m.predict(x)
  m.plot(y)
  m.plot_components(y)







m = Prophet()

m.fit(data)

